In [55]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [56]:
# dataset link: https://www.kaggle.com/datasets/sanchitagholap/crop-and-fertilizer-dataset-for-westernmaharashtra
df1 = pd.read_csv("datasets/fertilizer_dataset.csv")
df1.head()

,District_Name,Soil_color,Nitrogen,Phosphorus,Potassium,pH,Rainfall,Temperature,Crop,Fertilizer,Link
0,Kolhapur,Black,75,50,100,6.5,1000,20,Sugarcane,Urea,https://youtu.be/2t5Am0xLTOo
1,Kolhapur,Black,80,50,100,6.5,1000,20,Sugarcane,Urea,https://youtu.be/2t5Am0xLTOo
2,Kolhapur,Black,85,50,100,6.5,1000,20,Sugarcane,Urea,https://youtu.be/2t5Am0xLTOo
3,Kolhapur,Black,90,50,100,6.5,1000,20,Sugarcane,Urea,https://youtu.be/2t5Am0xLTOo
4,Kolhapur,Black,95,50,100,6.5,1000,20,Sugarcane,Urea,https://youtu.be/2t5Am0xLTOo

In [57]:
# dataset link: https://www.kaggle.com/datasets/gdabhishek/fertilizer-prediction
df2 = pd.read_csv("datasets/fertilizer.csv")
df2.head()

,Temparature,Humidity,Moisture,Soil Type,Crop Type,Nitrogen,Potassium,Phosphorous,Fertilizer Name
0,26,52,38,Sandy,Maize,37,0,0,Urea
1,29,52,45,Loamy,Sugarcane,12,0,36,DAP
2,34,65,62,Black,Cotton,7,9,30,14-35-14
3,32,62,34,Red,Tobacco,22,0,20,28-28
4,28,54,46,Clayey,Paddy,35,0,0,Urea

In [58]:
print(df1.shape)
df1.columns

(4513, 11)

Index(['District_Name', 'Soil_color', 'Nitrogen', 'Phosphorus', 'Potassium',
       'pH', 'Rainfall', 'Temperature', 'Crop', 'Fertilizer', 'Link'],
      dtype='object')

In [59]:
print(df2.shape)
df2.columns

(205, 9)

Index(['Temparature', 'Humidity ', 'Moisture', 'Soil Type', 'Crop Type',
       'Nitrogen', 'Potassium', 'Phosphorous', 'Fertilizer Name'],
      dtype='object')

In [60]:
df1 = df1.rename(columns={"Phosphorus": 'Phosphorous'})
df2 = df2.rename(columns={"Temparature": 'Temperature', 'Crop Type': 'Crop', 'Fertilizer Name': 'Fertilizer', 'Humidity ': 'Humidity'})

### Select the columns that are common in both datasets.

In [61]:
common_columns = ['Phosphorous', 'Nitrogen', 'Potassium', 'Temperature', 'Crop', 'Fertilizer']

In [62]:
# df1 = df1[common_columns]
# df2 = df2[common_columns]

In [63]:
df1.head(5)

,District_Name,Soil_color,Nitrogen,Phosphorous,Potassium,pH,Rainfall,Temperature,Crop,Fertilizer,Link
0,Kolhapur,Black,75,50,100,6.5,1000,20,Sugarcane,Urea,https://youtu.be/2t5Am0xLTOo
1,Kolhapur,Black,80,50,100,6.5,1000,20,Sugarcane,Urea,https://youtu.be/2t5Am0xLTOo
2,Kolhapur,Black,85,50,100,6.5,1000,20,Sugarcane,Urea,https://youtu.be/2t5Am0xLTOo
3,Kolhapur,Black,90,50,100,6.5,1000,20,Sugarcane,Urea,https://youtu.be/2t5Am0xLTOo
4,Kolhapur,Black,95,50,100,6.5,1000,20,Sugarcane,Urea,https://youtu.be/2t5Am0xLTOo

In [64]:
df2.head(5)

,Temperature,Humidity,Moisture,Soil Type,Crop,Nitrogen,Potassium,Phosphorous,Fertilizer
0,26,52,38,Sandy,Maize,37,0,0,Urea
1,29,52,45,Loamy,Sugarcane,12,0,36,DAP
2,34,65,62,Black,Cotton,7,9,30,14-35-14
3,32,62,34,Red,Tobacco,22,0,20,28-28
4,28,54,46,Clayey,Paddy,35,0,0,Urea

In [65]:
df1.describe()

,Nitrogen,Phosphorous,Potassium,pH,Rainfall,Temperature
count,4513.000000,4513.000000,4513.000000,4513.000000,4513.000000,4513.000000
mean,95.409927,54.341901,63.595170,6.715267,819.189010,25.915134
std,38.060648,16.551991,35.691911,0.625198,251.730813,5.897328
min,20.000000,10.000000,5.000000,5.500000,300.000000,10.000000
25%,60.000000,40.000000,40.000000,6.000000,600.000000,20.000000
50%,105.000000,55.000000,55.000000,6.500000,800.000000,25.000000
75%,125.000000,65.000000,75.000000,7.000000,1000.000000,30.000000
max,150.000000,90.000000,150.000000,8.500000,1700.000000,40.000000

### Merge two datasets according to their common columns. You can use other columns if you feel more appropriate.

In [66]:
merge = False
if merge:
    df = pd.concat([df1, df2], axis=0)
else:
    df = df1

df.head(5)

,District_Name,Soil_color,Nitrogen,Phosphorous,Potassium,pH,Rainfall,Temperature,Crop,Fertilizer,Link
0,Kolhapur,Black,75,50,100,6.5,1000,20,Sugarcane,Urea,https://youtu.be/2t5Am0xLTOo
1,Kolhapur,Black,80,50,100,6.5,1000,20,Sugarcane,Urea,https://youtu.be/2t5Am0xLTOo
2,Kolhapur,Black,85,50,100,6.5,1000,20,Sugarcane,Urea,https://youtu.be/2t5Am0xLTOo
3,Kolhapur,Black,90,50,100,6.5,1000,20,Sugarcane,Urea,https://youtu.be/2t5Am0xLTOo
4,Kolhapur,Black,95,50,100,6.5,1000,20,Sugarcane,Urea,https://youtu.be/2t5Am0xLTOo

In [67]:
df.shape

(4513, 11)

In [68]:
df.Fertilizer.unique()

array(['Urea', 'DAP', 'MOP', '10:26:26 NPK', 'SSP', 'Magnesium Sulphate',
       '13:32:26 NPK', '12:32:16 NPK', '50:26:26 NPK', '19:19:19 NPK',
       'Chilated Micronutrient', '18:46:00 NPK', 'Sulphur',
       '20:20:20 NPK', 'Ammonium Sulphate', 'Ferrous Sulphate',
       'White Potash', '10:10:10 NPK', 'Hydrated Lime'], dtype=object)

In [69]:
df.isna().sum()

District_Name    0
Soil_color       0
Nitrogen         0
Phosphorous      0
Potassium        0
pH               0
Rainfall         0
Temperature      0
Crop             0
Fertilizer       0
Link             0
dtype: int64

In [70]:
df['District_Name'].unique()

array(['Kolhapur', 'Solapur', 'Satara', 'Sangli', 'Pune'], dtype=object)

In [71]:
# source: https://www.indianclimate.com/

avg_humidity = {
    'Kolhapur': 71.8,
    'Solapur': 56.3,
    'Satara': 70.3,
    'Sangli': 69.8,
    'Pune': 69.3
}

In [72]:
df[df['District_Name'].notna()].shape

(4513, 11)

In [73]:
df.columns

Index(['District_Name', 'Soil_color', 'Nitrogen', 'Phosphorous', 'Potassium',
       'pH', 'Rainfall', 'Temperature', 'Crop', 'Fertilizer', 'Link'],
      dtype='object')

In [74]:
def fill_missing_humidity(item):
    district = item['District_Name']

    if district in avg_humidity.keys():
        print()
        return avg_humidity[district]
    else:
        print(item['Humidity'])
        return item['Humidity']

if merge:
    df['Humidity'] = df[['District_Name', 'Humidity']].apply(fill_missing_humidity, axis=1)
else:
    df['Humidity'] = df[['District_Name']].apply(fill_missing_humidity, axis=1)

In [75]:
df.isna().sum()

District_Name    0
Soil_color       0
Nitrogen         0
Phosphorous      0
Potassium        0
pH               0
Rainfall         0
Temperature      0
Crop             0
Fertilizer       0
Link             0
Humidity         0
dtype: int64

### Fertilizers: '10-26-26' and '10:26:26 NPK'should be the same, I'm not sure please research more.

In [76]:
df['Fertilizer'].unique()

array(['Urea', 'DAP', 'MOP', '10:26:26 NPK', 'SSP', 'Magnesium Sulphate',
       '13:32:26 NPK', '12:32:16 NPK', '50:26:26 NPK', '19:19:19 NPK',
       'Chilated Micronutrient', '18:46:00 NPK', 'Sulphur',
       '20:20:20 NPK', 'Ammonium Sulphate', 'Ferrous Sulphate',
       'White Potash', '10:10:10 NPK', 'Hydrated Lime'], dtype=object)

In [77]:
df['Fertilizer'] = df['Fertilizer'].replace('10-26-26', '10:26:26 NPK')

In [78]:
df['Humidity'].unique()

array([71.8, 56.3, 70.3, 69.8, 69.3])

### Export merged dataset to csv file

In [79]:
if merge:
    df.to_csv("datasets/merge_fertilized.csv")
else:
    df.to_csv("datasets/fertilizer_dataset2.csv")